### ISSUE TITLE
Training on multiple GPUs in parallel

### ISSUE THREAD

**Issue by vnik18** [j6mes/acl2021-factual-error-correction#3]
Hello, I am able to run your code, however I do not have access to a TPU. 

Do you know if it is possible to perform training of the masker-corrector model on multiple GPUs instead of a single one? Thank you!

**Comment by j6mes** [comment]
Hi, while i did all my experiments on a single GPU. The code is built on huggingface and should support distributed data parallel training automatically detecting multiple GPUs or by manually setting the `--num_gpus X` flag

**Comment by vnik18** [comment]
Thank you, I will try that
