### ISSUE TITLE
Unable to run the FEVER task classifier scripts (LIME-based masker)

### ISSUE THREAD

**Issue by JudePark96** [j6mes/acl2021-factual-error-correction#5]
Hi,

To reproduce an experiments from the scratch that you've done, I was trying to run the LIME-based masker w/ bash scripts following as:

```
bash scripts/finetune_fever.sh 5e-5 fever_sub genre_50_2 true
```

```
finetune_fever.sh

lr=$1
reader=$2
ns=$3
dpr=$4

python -m fec.modelling.finetune_fever \
  --model_name_or_path bert-base-uncased \
  --learning_rate $lr \
  --num_train_epochs 3 \
  --output_dir output/fever/reader=${reader},lr=${lr},data=${dpr},negative_sampling=${ns}/seed=1/  \
  --train_file resources/retrieval/genre_50/${dpr}_train.jsonl \
  --val_file resources/retrieval/genre_50/${dpr}_dev.jsonl \
  --do_train \
  --train_batch_size 16 \
  --eval_batch_size 16 \
  --reader $reader \
  --negative_sampling ${ns} \
  --seed 1
```

But "ModuleNotFoundError" (fec.modelling.finetune_fever) comes out, and I also have tried to find **fec** module, but I couldn't find.

If you can, I hope you to check the bash script is wrong or not.

Thank you for your paper and code!

**Comment by j6mes** [comment]
Hi, please check the python path as this needs to contain the `src/` folder which contains the fec module (run `export PYTHONPATH=src`)

**Comment by JudePark96** [comment]
@j6mes thank you for your reply.

I followed your environment set up process (create new conda repo, export PYTHONPATH=src), but it didn't work.
But I checked ```bash scripts/finetune_supervised.sh t5-base 1e-4 true false all (Fully-supervised ceiling)``` is working. So I think it is not my environment problem.

Can you please check your repository contains `fec` module or not?

Thanks.

**Comment by j6mes** [comment]
Ah! Looks like it was an error in the script (when i made it public, i renamed the module from `fec` to `error_correction`) 

I've updated the script now.

**Comment by JudePark96** [comment]
I checked update! Thanks!

**Comment by JudePark96** [comment]
@j6mes I think `finetune_fever` module doesn't exist. Can you please check again ?
